name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 KST
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: yoshi389111/github-profile-3d-contrib@v0.9.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Loop animation
        run: |
          perl -pi -e 's{values="([^"]*)" dur="3s" repeatCount="1"}{my @v=split /;/,$1; push @v, ($v[-1]) x $#v; qq{values="}.join(";",@v).qq{" dur="6s" repeatCount="indefinite"}}ge' profile-3d-contrib/profile-green-animate.svg
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push
          fi
